config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios, :controllers => { :omniauth_callbacks => "usuarios/omniauth_callbacks", 
    :sessions => "usuarios/sessions", :registrations => 'usuarios/registrations' }
  
  resources :mensagem_anuncios
  resources :categoria_anuncios
  resources :curtida_anuncios
  resources :anuncios
  resources :forma_pagamentos
  resources :cupoms
  resources :mensagem_cupoms
  resources :categoria_cupoms
  resources :descontos
  resources :banners, except: [:show]
  resources :carreiras
  resources :adesaos
  resources :retiradas
  resources :logs, except: [:edit, :update, :show]
  resources :mensagems
  resources :cidades
  resources :estados
  resources :pais
  resources :enderecos
  resources :negocios
  resources :conta
  resources :grupos
  resources :tipo_usuarios
  resources :usuarios
  resources :comments, only: [:create, :destroy]

  root :to => 'categoria_anuncios#index'

  get '/pais/estados/:pai_id', to: 'pais#estados'
  get '/estados/cidades/:estado_id', to: 'estados#cidades'

  
  get '/auth/failure', to: redirect('/')

  devise_scope :usuario do
    get '/auth/facebook/callback', to: 'usuarios/sessions#create'

    get '/usuarios/sign_out', :to => 'devise/sessions#destroy'# :as => :destroy_usuario_session
  
  end

  match :like, to: 'likes#create', as: :like, via: :post
  match :unlike, to: 'likes#destroy', as: :unlike, via: :post
  match :follow, to: 'follows#create', as: :follow, via: :post
  match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post

end

app/models/adesao.rb
class Adesao < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :tipo_usuario
end

app/controllers/adesaos_controller.rb
class AdesaosController < ApplicationController
  before_action :set_adesao, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!

  # GET /adesaos
  # GET /adesaos.json
  def index
    @adesaos = Adesao.all
  end

  # GET /adesaos/1
  # GET /adesaos/1.json
  def show
  end

  # GET /adesaos/new
  def new
    @adesao = Adesao.new
  end

  # GET /adesaos/1/edit
  def edit
  end

  # POST /adesaos
  # POST /adesaos.json
  def create
    @adesao = Adesao.new(adesao_params)

    respond_to do |format|
      if @adesao.save
        format.html { redirect_to @adesao, notice: 'Adesao was successfully created.' }
        format.json { render :show, status: :created, location: @adesao }
      else
        format.html { render :new }
        format.json { render json: @adesao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adesaos/1
  # PATCH/PUT /adesaos/1.json
  def update
    respond_to do |format|
      if @adesao.update(adesao_params)
        format.html { redirect_to @adesao, notice: 'Adesao was successfully updated.' }
        format.json { render :show, status: :ok, location: @adesao }
      else
        format.html { render :edit }
        format.json { render json: @adesao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adesaos/1
  # DELETE /adesaos/1.json
  def destroy
    @adesao.destroy
    respond_to do |format|
      format.html { redirect_to adesaos_url, notice: 'Adesao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adesao
      @adesao = Adesao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adesao_params
      params.require(:adesao).permit(:data, :valor, :validade, :usuario_id, :tipo_usuario_id)
    end
end

app/helpers/adesaos_helper.rb
module AdesaosHelper
end

app/views/adesaos/_form.html.erb
<%= form_for(@adesao) do |f| %>
  <% if @adesao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@adesao.errors.count, "error") %> prohibited this adesao from being saved:</h2>

      <ul>
      <% @adesao.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data %><br>
    <%= f.datetime_select :data %>
  </div>
  <div class="field">
    <%= f.label :valor %><br>
    <%= f.text_field :valor %>
  </div>
  <div class="field">
    <%= f.label :validade %><br>
    <%= f.datetime_select :validade %>
  </div>
  <div class="field">
    <%= f.label :usuario_id %><br>
    <%= f.number_field :usuario_id %>
  </div>
  <div class="field">
    <%= f.label :tipo_usuario_id %><br>
    <%= f.number_field :tipo_usuario_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/adesaos/edit.html.erb
<h1>Editing Adesao</h1>

<%= render 'form' %>

<%= link_to 'Show', @adesao %> |
<%= link_to 'Back', adesaos_path %>

app/views/adesaos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Adesaos</h1>

<table>
  <thead>
    <tr>
      <th>Data</th>
      <th>Valor</th>
      <th>Validade</th>
      <th>Usuario</th>
      <th>Tipo usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @adesaos.each do |adesao| %>
      <tr>
        <td><%= adesao.data %></td>
        <td><%= adesao.valor %></td>
        <td><%= adesao.validade %></td>
        <td><%= adesao.usuario_id %></td>
        <td><%= adesao.tipo_usuario_id %></td>
        <td><%= link_to 'Show', adesao %></td>
        <td><%= link_to 'Edit', edit_adesao_path(adesao) %></td>
        <td><%= link_to 'Destroy', adesao, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Adesao', new_adesao_path %>

app/views/adesaos/new.html.erb
<h1>New Adesao</h1>

<%= render 'form' %>

<%= link_to 'Back', adesaos_path %>

app/views/adesaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @adesao.data %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @adesao.valor %>
</p>

<p>
  <strong>Validade:</strong>
  <%= @adesao.validade %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @adesao.usuario_id %>
</p>

<p>
  <strong>Tipo usuario:</strong>
  <%= @adesao.tipo_usuario_id %>
</p>

<%= link_to 'Edit', edit_adesao_path(@adesao) %> |
<%= link_to 'Back', adesaos_path %>