config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios, :controllers => { :omniauth_callbacks => "usuarios/omniauth_callbacks", 
    :sessions => "usuarios/sessions", :registrations => 'usuarios/registrations' }
  
  resources :mensagem_anuncios
  resources :categoria_anuncios
  resources :curtida_anuncios
  resources :anuncios
  resources :forma_pagamentos
  resources :cupoms
  resources :mensagem_cupoms
  resources :categoria_cupoms
  resources :descontos
  resources :banners, except: [:show]
  resources :carreiras
  resources :adesaos
  resources :retiradas
  resources :logs, except: [:edit, :update, :show]
  resources :mensagems
  resources :cidades
  resources :estados
  resources :pais
  resources :enderecos
  resources :negocios
  resources :conta
  resources :grupos
  resources :tipo_usuarios
  resources :usuarios
  resources :comments, only: [:create, :destroy]

  root :to => 'categoria_anuncios#index'

  get '/pais/estados/:pai_id', to: 'pais#estados'
  get '/estados/cidades/:estado_id', to: 'estados#cidades'

  
  get '/auth/failure', to: redirect('/')

  devise_scope :usuario do
    get '/auth/facebook/callback', to: 'usuarios/sessions#create'

    get '/usuarios/sign_out', :to => 'devise/sessions#destroy'# :as => :destroy_usuario_session
  
  end

  match :like, to: 'likes#create', as: :like, via: :post
  match :unlike, to: 'likes#destroy', as: :unlike, via: :post
  match :follow, to: 'follows#create', as: :follow, via: :post
  match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post

end

app/models/forma_pagamento.rb
class FormaPagamento < ActiveRecord::Base
  has_many :anuncios
  has_many :cupoms

  retina!
  has_attached_file :imagem,
                    :styles => { :medium => "300x300#", :thumb => "100x100#"},
                    :retina => { :quality => 100 }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :imagem,
                                    :content_type => ["image/jpg", "image/jpeg", "image/png"],
                                    message: "Formato inválido!"
                                    
end

app/controllers/forma_pagamentos_controller.rb
class FormaPagamentosController < ApplicationController
  before_action :set_forma_pagamento, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!
  before_action :is_marketing

  # GET /forma_pagamentos
  # GET /forma_pagamentos.json
  def index
    @forma_pagamentos = FormaPagamento.all
    create_log("Listar formas de pagamento")
  end

  # GET /forma_pagamentos/1
  # GET /forma_pagamentos/1.json
  def show
    create_log("Visualizar forma de pagamento")
  end

  # GET /forma_pagamentos/new
  def new
    @forma_pagamento = FormaPagamento.new
    create_log("Formulário de criação de nova forma de pagamento")
  end

  # GET /forma_pagamentos/1/edit
  def edit
    create_log("Formulário de edição da forma de pagamento")
  end

  # POST /forma_pagamentos
  # POST /forma_pagamentos.json
  def create
    @forma_pagamento = FormaPagamento.new(forma_pagamento_params)

    respond_to do |format|
      if @forma_pagamento.save
        format.html { redirect_to @forma_pagamento, notice: 'Forma pagamento was successfully created.' }
        format.json { render :show, status: :created, location: @forma_pagamento }
      else
        format.html { render :new }
        format.json { render json: @forma_pagamento.errors, status: :unprocessable_entity }
      end
    end
      create_log("Criou nova forma de pagamento")
  end

  # PATCH/PUT /forma_pagamentos/1
  # PATCH/PUT /forma_pagamentos/1.json
  def update
    respond_to do |format|
      if @forma_pagamento.update(forma_pagamento_params)
        format.html { redirect_to @forma_pagamento, notice: 'Forma pagamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @forma_pagamento }
      else
        format.html { render :edit }
        format.json { render json: @forma_pagamento.errors, status: :unprocessable_entity }
      end
    end
    create_log("Editou forma de pagamento")
  end

  # DELETE /forma_pagamentos/1
  # DELETE /forma_pagamentos/1.json
  def destroy
    @forma_pagamento.destroy
    respond_to do |format|
      format.html { redirect_to forma_pagamentos_url, notice: 'Forma pagamento was successfully destroyed.' }
      format.json { head :no_content }
    end
    create_log("Excluiu forma de pagamento")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forma_pagamento
      @forma_pagamento = FormaPagamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forma_pagamento_params
      params.require(:forma_pagamento).permit(:imagem, :retina_dimensions, :nome)
    end
end

app/helpers/forma_pagamentos_helper.rb
module FormaPagamentosHelper
end

app/views/forma_pagamentos/_form.html.erb
<%= form_for(@forma_pagamento) do |f| %>
  <% if @forma_pagamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forma_pagamento.errors.count, "error") %> prohibited this forma_pagamento from being saved:</h2>

      <ul>
      <% @forma_pagamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :imagem %><br>
    <%= f.file_field :imagem, :accept => "image/*" %>
  </div>
  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forma_pagamentos/edit.html.erb
<h1>Editing Forma Pagamento</h1>

<%= render 'form' %>

<%= link_to 'Show', @forma_pagamento %> |
<%= link_to 'Back', forma_pagamentos_path %>

app/views/forma_pagamentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Forma Pagamentos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @forma_pagamentos.each do |forma_pagamento| %>
      <tr>
        <td><%= forma_pagamento.nome %></td>
        <td><%= link_to 'Show', forma_pagamento %></td>
        <td><%= link_to 'Edit', edit_forma_pagamento_path(forma_pagamento) %></td>
        <td><%= link_to 'Destroy', forma_pagamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Forma pagamento', new_forma_pagamento_path %>

app/views/forma_pagamentos/new.html.erb
<h1>New Forma Pagamento</h1>

<%= render 'form' %>

<%= link_to 'Back', forma_pagamentos_path %>

app/views/forma_pagamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @forma_pagamento.nome %>
</p>

<%= link_to 'Edit', edit_forma_pagamento_path(@forma_pagamento) %> |
<%= link_to 'Back', forma_pagamentos_path %>