config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios, :controllers => { :omniauth_callbacks => "usuarios/omniauth_callbacks", 
    :sessions => "usuarios/sessions", :registrations => 'usuarios/registrations' }
  
  resources :mensagem_anuncios
  resources :categoria_anuncios
  resources :curtida_anuncios
  resources :anuncios
  resources :forma_pagamentos
  resources :cupoms
  resources :mensagem_cupoms
  resources :categoria_cupoms
  resources :descontos
  resources :banners, except: [:show]
  resources :carreiras
  resources :adesaos
  resources :retiradas
  resources :logs, except: [:edit, :update, :show]
  resources :mensagems
  resources :cidades
  resources :estados
  resources :pais
  resources :enderecos
  resources :negocios
  resources :conta
  resources :grupos
  resources :tipo_usuarios
  resources :usuarios
  resources :comments, only: [:create, :destroy]

  root :to => 'categoria_anuncios#index'

  get '/pais/estados/:pai_id', to: 'pais#estados'
  get '/estados/cidades/:estado_id', to: 'estados#cidades'

  
  get '/auth/failure', to: redirect('/')

  devise_scope :usuario do
    get '/auth/facebook/callback', to: 'usuarios/sessions#create'

    get '/usuarios/sign_out', :to => 'devise/sessions#destroy'# :as => :destroy_usuario_session
  
  end

  match :like, to: 'likes#create', as: :like, via: :post
  match :unlike, to: 'likes#destroy', as: :unlike, via: :post
  match :follow, to: 'follows#create', as: :follow, via: :post
  match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post

end

app/models/estado.rb
class Estado < ActiveRecord::Base
  belongs_to :pais
  has_many :cidades
  has_many :enderecos
end

app/controllers/estados_controller.rb
class EstadosController < ApplicationController
  before_action :set_estado, only: [:show, :edit, :update, :destroy]

  # GET /estados
  # GET /estados.json
  def index
    @estados = Estado.all
  end

  # GET /estados/1
  # GET /estados/1.json
  def show
  end

  # GET /estados/new
  def new
    @estado = Estado.new
  end

  # GET /estados/1/edit
  def edit
  end

  # POST /estados
  # POST /estados.json
  def create
    @estado = Estado.new(estado_params)

    respond_to do |format|
      if @estado.save
        format.html { redirect_to @estado, notice: 'Estado was successfully created.' }
        format.json { render :show, status: :created, location: @estado }
      else
        format.html { render :new }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estados/1
  # PATCH/PUT /estados/1.json
  def update
    respond_to do |format|
      if @estado.update(estado_params)
        format.html { redirect_to @estado, notice: 'Estado was successfully updated.' }
        format.json { render :show, status: :ok, location: @estado }
      else
        format.html { render :edit }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estados/1
  # DELETE /estados/1.json
  def destroy
    @estado.destroy
    respond_to do |format|
      format.html { redirect_to estados_url, notice: 'Estado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def cidades
    estado = Estado.find_by_id(params[:estado_id])
    render json: estado.cidades
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estado
      @estado = Estado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estado_params
      params.require(:estado).permit(:nome, :sigla, :pais_id)
    end
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/views/estados/_form.html.erb
<%= form_for(@estado) do |f| %>
  <% if @estado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@estado.errors.count, "error") %> prohibited this estado from being saved:</h2>

      <ul>
      <% @estado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label :sigla %><br>
    <%= f.text_field :sigla %>
  </div>

  <div class="field">
    <%= f.label :pais_id %><br>
    <%= f.number_field :pais_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/estados/edit.html.erb
<h1>Editing Estado</h1>

<%= render 'form' %>

<%= link_to 'Show', @estado %> |
<%= link_to 'Back', estados_path %>

app/views/estados/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Estados</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Pais</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estados.each do |estado| %>
      <tr>
        <td><%= estado.nome %></td>
        <td><%= estado.pais_id %></td>
        <td><%= link_to 'Show', estado %></td>
        <td><%= link_to 'Edit', edit_estado_path(estado) %></td>
        <td><%= link_to 'Destroy', estado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Estado', new_estado_path %>

app/views/estados/new.html.erb
<h1>New Estado</h1>

<%= render 'form' %>

<%= link_to 'Back', estados_path %>

app/views/estados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @estado.nome %>
</p>

<p>
  <strong>Pais:</strong>
  <%= @estado.pais_id %>
</p>

<%= link_to 'Edit', edit_estado_path(@estado) %> |
<%= link_to 'Back', estados_path %>