config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios, :controllers => { :omniauth_callbacks => "usuarios/omniauth_callbacks", 
    :sessions => "usuarios/sessions", :registrations => 'usuarios/registrations' }
  
  resources :mensagem_anuncios
  resources :categoria_anuncios
  resources :curtida_anuncios
  resources :anuncios
  resources :forma_pagamentos
  resources :cupoms
  resources :mensagem_cupoms
  resources :categoria_cupoms
  resources :descontos
  resources :banners, except: [:show]
  resources :carreiras
  resources :adesaos
  resources :retiradas
  resources :logs, except: [:edit, :update, :show]
  resources :mensagems
  resources :cidades
  resources :estados
  resources :pais
  resources :enderecos
  resources :negocios
  resources :conta
  resources :grupos
  resources :tipo_usuarios
  resources :usuarios
  resources :comments, only: [:create, :destroy]

  root :to => 'categoria_anuncios#index'

  get '/pais/estados/:pai_id', to: 'pais#estados'
  get '/estados/cidades/:estado_id', to: 'estados#cidades'

  
  get '/auth/failure', to: redirect('/')

  devise_scope :usuario do
    get '/auth/facebook/callback', to: 'usuarios/sessions#create'

    get '/usuarios/sign_out', :to => 'devise/sessions#destroy'# :as => :destroy_usuario_session
  
  end

  match :like, to: 'likes#create', as: :like, via: :post
  match :unlike, to: 'likes#destroy', as: :unlike, via: :post
  match :follow, to: 'follows#create', as: :follow, via: :post
  match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post

end

app/models/anuncio.rb
class Anuncio < ActiveRecord::Base
  belongs_to :categoria_anuncio
  belongs_to :endereco
  belongs_to :forma_pagamento
  belongs_to :usuario
  has_many :curtida_anuncios

  acts_as_votable
end

app/controllers/anuncios_controller.rb
class AnunciosController < ApplicationController
  before_action :set_anuncio, only: [:show, :edit, :update, :destroy]

  # GET /anuncios
  # GET /anuncios.json
  def index
    @anuncios = Anuncio.all
  end

  # GET /anuncios/1
  # GET /anuncios/1.json
  def show
  end

  # GET /anuncios/new
  def new
    @anuncio = Anuncio.new
  end

  # GET /anuncios/1/edit
  def edit
  end

  # POST /anuncios
  # POST /anuncios.json
  def create
    @anuncio = Anuncio.new(anuncio_params)

    respond_to do |format|
      if @anuncio.save
        format.html { redirect_to @anuncio, notice: 'Anuncio was successfully created.' }
        format.json { render :show, status: :created, location: @anuncio }
      else
        format.html { render :new }
        format.json { render json: @anuncio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /anuncios/1
  # PATCH/PUT /anuncios/1.json
  def update
    respond_to do |format|
      if @anuncio.update(anuncio_params)
        format.html { redirect_to @anuncio, notice: 'Anuncio was successfully updated.' }
        format.json { render :show, status: :ok, location: @anuncio }
      else
        format.html { render :edit }
        format.json { render json: @anuncio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /anuncios/1
  # DELETE /anuncios/1.json
  def destroy
    @anuncio.destroy
    respond_to do |format|
      format.html { redirect_to anuncios_url, notice: 'Anuncio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_anuncio
      @anuncio = Anuncio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def anuncio_params
      params.require(:anuncio).permit(:titulo, :subtitulo, :valor, :descricao, :categoria_anuncio_id, :endereco_id, :forma_pagamento_id, :usuario_id)
    end
end

app/helpers/anuncios_helper.rb
module AnunciosHelper
end

app/views/anuncios/_form.html.erb
<%= form_for(@anuncio) do |f| %>
  <% if @anuncio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@anuncio.errors.count, "error") %> prohibited this anuncio from being saved:</h2>

      <ul>
      <% @anuncio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :subtitulo %><br>
    <%= f.text_field :subtitulo %>
  </div>
  <div class="field">
    <%= f.label :valor %><br>
    <%= f.text_field :valor %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_field :descricao %>
  </div>
  <div class="field">
    <%= f.label :categoria_anuncio_id %><br>
    <%= f.number_field :categoria_anuncio_id %>
  </div>
  <div class="field">
    <%= f.label :endereco_id %><br>
    <%= f.number_field :endereco_id %>
  </div>
  <div class="field">
    <%= f.label :forma_pagamento_id %><br>
    <%= f.number_field :forma_pagamento_id %>
  </div>
  <div class="field">
    <%= f.label :usuario_id %><br>
    <%= f.number_field :usuario_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/anuncios/edit.html.erb
<h1>Editing Anuncio</h1>

<%= render 'form' %>

<%= link_to 'Show', @anuncio %> |
<%= link_to 'Back', anuncios_path %>

app/views/anuncios/index.html.erb
<p id="notice"><%= notice %></p>


    <% @anuncios.each do |anuncio| %>

      <%= anuncio.titulo %>
      <%= anuncio.subtitulo %>
      <%= anuncio.valor %>
      <%= anuncio.descricao %>
      <%= anuncio.categoria_anuncio_id %>
      <%= anuncio.endereco_id %>
      <%= anuncio.forma_pagamento_id %>
      <%= anuncio.usuario_id %>
      <%= link_to 'Show', anuncio %>
      <%= link_to 'Edit', edit_anuncio_path(anuncio) %>
      <%= link_to 'Destroy', anuncio, method: :delete, data: { confirm: 'Are you sure?' } %>
      
    <% end %>
  

<%= link_to 'New Anuncio', new_anuncio_path %>

<div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <h1 class="titulopage">Anúncios</h1>
                        <h4>Fortaleza > Lazer > Cinema</h4>
                    </div>
                    <div class="col-md-4"></div>
                    <div class="col-md-4"></div>
                </div>
            </div>
            <div>
                <div class="container-fluid">
                <div class="col-md-12">
                    <div class="gap2"></div>
                    <center>
                    <button type="button" class="btn btn-lg btn-ghost">Ingressos</button>
                    <button type="button" class="btn btn-lg btn-ghost">Filmes</button>
                    <button type="button" class="btn btn-lg btn-ghost">Bares</button>
                    <button type="button" class="btn btn-lg btn-ghost">Shoppings</button>
                    <button type="button" class="btn btn-lg btn-ghost">Pizzarias</button>
                    <button type="button" class="btn btn-lg btn-ghost">Cinemas</button>
                    <button type="button" class="btn btn-lg btn-ghost">Restaurantes</button>
                    <button type="button" class="btn btn-lg btn-ghost">Bares</button>
                    <button type="button" class="btn btn-lg btn-ghost">Shoppings</button>
                    <button type="button" class="btn btn-lg btn-ghost">Pizzarias</button>
                    </center>
                    <div class="gap2"></div>
                </div>
            </div>
            </div>
        <div class="gap2"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <div class="row row-wrap">
                        <a class="col-md-12" href="#">
                            <div class="product-thumb">
                                <header class="product-header">
                                    <img src=<%=image_url("img/banner.png")%> >
                                </header>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-md-9">
                    <div class="row row-wrap">
                      <a class="col-md-4" href="#">
                        <div class="product-thumb">
                            <header class="product-header">
                              <img src="http://lorempixel.com/600/600/" alt="Image Alternative text" title="Green Furniture" />
                            </header>
                            <div class="product-inner">
                              <p class="product-desciption">Potenti sed blandit venenatis fames suspendisse integer dictumst</p>
                              <img src=<%=image_url("img/avatar36x36.png")%> class="buton3" alt=""> DOM BIFE
                              <span class="glyphicon glyphicon-heart pull-right redd" aria-hidden="true"><SMALL>6</SMALL></span>
                            </div>
                            <div class="selo2">
                              R$ 15,90
                            </div>
                            <div class="selo3">
                              <span><small>PRO-1</small></span><br>
                            </div>
                        </div>
                      </a>
                    </div>
                  </div>
                </div>
              </div>

app/views/anuncios/new.html.erb
<h1 class="titulopage">Cadastro Anuncio</h1>
<div class="container">
	<%= render 'form' %>

	<%= link_to 'Back', anuncios_path %>
</div>

app/views/anuncios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @anuncio.titulo %>
</p>

<p>
  <strong>Subtitulo:</strong>
  <%= @anuncio.subtitulo %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @anuncio.valor %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @anuncio.descricao %>
</p>

<p>
  <strong>Categoria anuncio:</strong>
  <%= @anuncio.categoria_anuncio_id %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @anuncio.endereco_id %>
</p>

<p>
  <strong>Forma pagamento:</strong>
  <%= @anuncio.forma_pagamento_id %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @anuncio.usuario_id %>
</p>

<%= link_to 'Edit', edit_anuncio_path(@anuncio) %> |
<%= link_to 'Back', anuncios_path %>